### ISSUE TITLE
Error 500 - An exception was raised while creating "AcMailer\Service\MailService"; no instance returned

### ISSUE THREAD

**Issue by EvKoh** [acelaya/ZF2-AcMailer#95]
UserController.php, line 77 :
```
$mailService = $this->getServiceLocator()->get('AcMailer\Service\MailService');
```

Error 500 :
```
An exception was raised while creating "AcMailer\Service\MailService"; no instance returned
```

```
#0 /vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(1097): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'acmailerservice...', 'AcMailer\\Servic...')
#1 /vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(638): Zend\ServiceManager\ServiceManager->createFromFactory('acmailerservice...', 'AcMailer\\Servic...')
#2 /vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('AcMailer\\Servic...', 'acmailerservice...')
#3 /vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)

#4 /module/Manager/src/Manager/Controller/UserController.php(77): Zend\ServiceManager\ServiceManager->get('AcMailer\\Servic...')
#5 /vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(82): Manager\Controller\UserController->myAccountAction()

#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)
#7 /vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)
#8 /vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)
#9 /vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)
#10 /vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)
#12 /vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)
#13 /vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)
#14 /vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)
#15 /public/index.php(78): Zend\Mvc\Application->run()
#16 {main}
```

config/application.config.php :
```
$config = array(
    // This should be an array of module namespaces used in the application.
    'modules' => array(
        'AcMailer', // Mails
        //'Application',   
        'ZfcBase', // Base
        'ZfcUser', // Login / Register
        // ...
```

composer.json :
```
    "php": ">=5.5",
    "zendframework/zendframework": "2.4.*",
    "zf-commons/zfc-base": "0.*",
    "zf-commons/zfc-user": "1.2.2",
    "acelaya/zf2-acmailer": "4.5.0",
```

Same probleme with ZF 2.3.* OR 2.4.*
Same probleme with zf2-acmailer ~4.0 OR 4.5.0

**Comment by alejandro-fiore** [comment]
See https://github.com/acelaya/ZF2-AcMailer/issues/94#issuecomment-102117242

**Comment by EvKoh** [comment]
Thanks, it's good !

**Comment by acelaya** [comment]
I'm glad to say that finally found a workaround that fixes the problems with ZF2.4 without introducing a BC break.
Version [4.5.1](https://github.com/acelaya/ZF2-AcMailer/releases/tag/v4.5.1) is available now.

**Comment by EvKoh** [comment]
+1 yeah !!
